"""
Django settings for config project.

Generated by 'django-admin startproject' and maintained for Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    try:
        # Compatibility with the django-dotenv package in the current local venv.
        from dotenv import read_dotenv as load_dotenv
    except ImportError:  # The sample dashboard can run before optional packages exist.
        load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if load_dotenv:
    load_dotenv(BASE_DIR / ".env")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-local-dashboard-preview-only",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

DASHBOARD_DATA_MODE = os.getenv("DASHBOARD_DATA_MODE", "sample").strip().lower()
if DASHBOARD_DATA_MODE not in {"sample", "live"}:
    DASHBOARD_DATA_MODE = "sample"

GOLD_DASHBOARD_VIEW = os.getenv(
    "GOLD_DASHBOARD_VIEW",
    "dashboard_gold_manager_view",
).strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'datapipeline',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def mysql_database():
    """Build the single local MySQL connection from MYSQL_* variables."""
    return {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_NAME", "").strip(),
        "USER": os.getenv("MYSQL_USER", "").strip(),
        "PASSWORD": os.getenv("MYSQL_PASSWORD", ""),
        "HOST": os.getenv("MYSQL_HOST", "").strip(),
        "PORT": os.getenv("MYSQL_PORT", "3306").strip(),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {"charset": "utf8mb4", "connect_timeout": 5},
    }


MYSQL_CONFIGURED = all(
    os.getenv(key, "").strip()
    for key in ("MYSQL_NAME", "MYSQL_USER", "MYSQL_HOST")
)
if DASHBOARD_DATA_MODE == "live" and MYSQL_CONFIGURED:
    DATABASES = {"default": mysql_database()}
else:
    # Sample mode must stay bootable even when saved local-network credentials
    # are temporarily unreachable.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# MongoDB is accessed through PyMongo in the repository layer, not Django ORM.
MONGODB = {
    "URI": os.getenv("MONGO_URI", "").strip(),
    "DATABASE": os.getenv("MONGO_DATABASE", "").strip(),
    "STANDARDIZATION_REJECTED_COLLECTION": os.getenv(
        "MONGO_STANDARDIZATION_REJECTED_COLLECTION",
        "standardization_rejected",
    ).strip(),
    "NORMALIZATION_REJECTED_COLLECTION": os.getenv(
        "MONGO_NORMALIZATION_REJECTED_COLLECTION",
        "normalization_rejected",
    ).strip(),
    "SERVER_SELECTION_TIMEOUT_MS": 5000,
    "CONNECT_TIMEOUT_MS": 5000,
}
MONGODB_CONFIGURED = bool(MONGODB["URI"] and MONGODB["DATABASE"])


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/5.2/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
